services:
  - type: web
    name: newslens
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    autoDeploy: true